### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by halfmoonvic** [timonwong/OmniMarkupPreviewer#111]
When I open markdown file by OmniMarkupPreviewer, there is some wrong with my google chrome and firefox.
In the console, it output some info, "Failed to load resource: the server responded with a status of 500 (Internal Server Error)".
Im sure there is no conflict at server_port.

The logs in the console as flowing:

> `Package Control: Skipping automatic upgrade, last run at 2016-12-14 13:46:46, next run at 2016-12-14 >14:46:46 or after
>OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:51004/view/31
><h1>Critical error while processing request: /public/github.css</h1>AssertionError('WSGI >start_response called a second time with no exc_info.',)
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 855, in wsgi
>    start_response(response._status_line, response.headerlist)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1906, >in start_response
>    self.req.outheaders.append((k.encode('ISO-8859-1'), v.encode('ISO-8859-1')))
>UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1035, >in communicate
>    req.respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 831, >in respond
>    self.server.gateway(self).respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1856, >in respond
>    response = self.req.server.wsgi_app(self.env, self.start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 874, in __call__
>    return self.wsgi(environ, start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 869, in wsgi
>    start_response('500 INTERNAL SERVER ERROR', headers)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1878, >in start_response
 >   raise AssertionError("WSGI start_response called a second "
>AssertionError: WSGI start_response called a second time with no exc_info.
><h1>Critical error while processing request: /public/jquery-2.1.3.min.js</h1>AssertionError('WSGI >start_response called a second time with no exc_info.',)
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 855, in wsgi
>    start_response(response._status_line, response.headerlist)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1906, >in start_response
>    self.req.outheaders.append((k.encode('ISO-8859-1'), v.encode('ISO-8859-1')))
>UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1035, >in communicate
>    req.respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 831, >in respond
>    self.server.gateway(self).respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1856, >in respond
>    response = self.req.server.wsgi_app(self.env, self.start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 874, in __call__
>    return self.wsgi(environ, start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 869, in wsgi
>    start_response('500 INTERNAL SERVER ERROR', headers)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1878, >in start_response
>    raise AssertionError("WSGI start_response called a second "
>AssertionError: WSGI start_response called a second time with no exc_info.
><h1>Critical error while processing request: /public/app.js</h1>AssertionError('WSGI start_response >called a second time with no exc_info.',)
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 855, in wsgi
>    start_response(response._status_line, response.headerlist)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1906, >in start_response
>    self.req.outheaders.append((k.encode('ISO-8859-1'), v.encode('ISO-8859-1')))
>UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
>
>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1035, >in communicate
>    req.respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 831, >in respond
>    self.server.gateway(self).respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1856, >in respond
>    response = self.req.server.wsgi_app(self.env, self.start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 874, in __call__
>    return self.wsgi(environ, start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 869, in wsgi
>    start_response('500 INTERNAL SERVER ERROR', headers)
> File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1878, >in start_response
>    raise AssertionError("WSGI start_response called a second "
>AssertionError: WSGI start_response called a second time with no exc_info.
><h1>Critical error while processing request: >/public/imagesloaded.pkgd.min.js</h1>AssertionError('WSGI start_response called a second time with >no exc_info.',)
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 855, in wsgi
>    start_response(response._status_line, response.headerlist)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1906, >in start_response
>    self.req.outheaders.append((k.encode('ISO-8859-1'), v.encode('ISO-8859-1')))
>UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1035, >in communicate
>    req.respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 831, >in respond
>    self.server.gateway(self).respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1856, >in respond
>    response = self.req.server.wsgi_app(self.env, self.start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 874, in __call__
>    return self.wsgi(environ, start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 869, in wsgi
>    start_response('500 INTERNAL SERVER ERROR', headers)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1878, >in start_response
>    raise AssertionError("WSGI start_response called a second "
>AssertionError: WSGI start_response called a second time with no exc_info.
><h1>Critical error while processing request: /public/app.js</h1>AssertionError('WSGI start_response >called a second time with no exc_info.',)
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 855, in wsgi
>    start_response(response._status_line, response.headerlist)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1906, >in start_response
>    self.req.outheaders.append((k.encode('ISO-8859-1'), v.encode('ISO-8859-1')))
>UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1035, >in communicate
>    req.respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 831, >in respond
>    self.server.gateway(self).respond()
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1856, >in respond
>    response = self.req.server.wsgi_app(self.env, self.start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 874, in __call__
>    return self.wsgi(environ, start_response)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\bottle.py", line 869, in wsgi
>    start_response('500 INTERNAL SERVER ERROR', headers)
>  File "C:\Users\John\AppData\Roaming\Sublime Text >3\Packages\OmniMarkupPreviewer\OmniMarkupLib\libs\cherrypy\wsgiserver\wsgiserver3.py", line 1878, >in start_response
>    raise AssertionError("WSGI start_response called a second "
>AssertionError: WSGI start_response called a second time with no exc_info.

**Comment by halfmoonvic** [comment]
I have solved it. There is a conflict between 'OmniMarkupPreviewer' and 'PlainTasks'. I just ignore the 'PlainTasks', I don't know how to fix this.

**Comment by yeshiqing** [comment]
@banyuewan I met the same question and I want to know how to fix it in details. I have the PlainTasks as well.

------- 
**add at 2017/2/19**

well,I got it. Just remove plainTasks package  and reinstall it~
It's sure they are conflicting but I still don't why, Since I'm not familiar with the python and sublime package run mechanism. I guess maybe the plainTasks has some updates.

**Comment by halfmoonvic** [comment]
@pageye123 you can ignore it at 'Preferences.sublime-settings' file. Anytime you need it, just reopen it, and restart the sublime.

**Comment by geekyouth** [comment]
@halfmoonvic 
如图：设置里面忽略掉\Sublime Text Build 3176 x64-portable\Data\Packages\PlainTasks 这个文件后马上就可以实时预览 markdown 文件

"ignored_packages":
	[
		"PlainTasks"
	],
![image](https://user-images.githubusercontent.com/12899262/45378357-cf27a480-b62f-11e8-8033-de96989c29ae.png)
![image](https://user-images.githubusercontent.com/12899262/45378364-d2229500-b62f-11e8-97f1-72b037b2aeb9.png)
