### ISSUE TITLE
Browser on Windows doesn't show anything

### ISSUE THREAD

**Issue by certainlyakey** [timonwong/OmniMarkupPreviewer#14]
When I try to preview a Markdown file, the new blank tab opens in browser with the address localhost:51004/view/27 or like, but never shows anything, just stays blank. I guess I don't have server running or something.

**Comment by raphaeltao** [comment]
基本上碰见这种问题都是因为装了类似的markdown插件占用了端口吧，我卸载了一个其他的就好使了
