### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by knlpsta** [timonwong/OmniMarkupPreviewer#65]
Small issue, but when I right-click to **Inspect Element** on the browser page, there's a Console error:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:51004/public/jquery.min.map

**Comment by timonwong** [comment]
Related to #66

**Comment by knlpsta** [comment]
I tried adding "jquery.min.map" (renamed from "jquery-2.1.3.min.map") and the uncompressed "jquery-2.1.3.js" to my **/Library/WebServer/Documents** folder (assuming that's where localhost is referencing on my Mac), but the Console error is still there..

**Comment by ashfinal** [comment]
"jquery.min.map" default should be placed into __~/Library/Application\ Support/Sublime\ Text\ 3/Packages/OmniMarkupPreviewer/public/__ folder.
A more convenient solution can be: Download ZIP-Extract & Rename the folder to OmniMarkupPreviewer-Replace __/Library/Application\ Support/Sublime\ Text\ 3/Packages/OmniMarkupPreviewer__ folder with the newer one

**Comment by knlpsta** [comment]
Oh, wow! Thanks so much. This is exactly what I was looking for.

I didn't know there was already a **/public** folder for **OmniMarkupPreviewer** but I followed your second recommendation (who doesn't love an upgrade??) and now there's no Console error, hah! :)
