### ISSUE TITLE
Support for .mmd files

### ISSUE THREAD

**Issue by orschiro** [timonwong/OmniMarkupPreviewer#70]
Hi @timonwong,

Is it possible to add support for multimarkdown `.mmd` files?

Thanks!

Robert

**Comment by timonwong** [comment]
MultiMarkdown is already supported, if just need a syntax file, you can get it in `MarkdownEditing` package, for example.

And I'll add support for `.mmd` files as well later, thanks for reporting.

**Comment by orschiro** [comment]
Thanks for the quick update!

Will this update be also pushed to package control?

**Comment by timonwong** [comment]
@orschiro 
Yes, several days later, still have some open issues to be addressed.
