### ISSUE TITLE
Feature: borrow 'github' mode from Markdown Preview

### ISSUE THREAD

**Issue by Gabriel-p** [timonwong/OmniMarkupPreviewer#73]
The extension [Markdown Preview](https://github.com/revolunet/sublimetext-markdown-preview) lest you choose between `github` and `markdown` when previewing a .md file.

The first option is really useful since it displays the file exactly as Github will show it.

Could something like this be added? (Or perhaps it already is added and I just don't know hot to use it, in which case: how do I use it?)

**Comment by Fire-** [comment]
+1

**Comment by timonwong** [comment]
The main difference between 'Markdown Preview' and 'OmniMarkupPreviewer' is the live preview feature, it requires a lot of HTTP requests, which can easily spam GitHub, or reach GitHub's rate limit, so I personally don't think it's a good idea to provide that.

**Comment by Gabriel-p** [comment]
Thanks for the answer!
