### ISSUE TITLE
Adding #! in the first line of code will number the code

### ISSUE THREAD

**Issue by yoonghm** [timonwong/OmniMarkupPreviewer#76]
![issue_281_1](https://cloud.githubusercontent.com/assets/4215991/8125832/c6d8ceec-111b-11e5-88ab-d3357cf499c3.jpg)

![issue_281_2](https://cloud.githubusercontent.com/assets/4215991/8125833/c9903af8-111b-11e5-9deb-b70416305baa.jpg)

**Comment by timonwong** [comment]
Thanks for reporting, I can confirm it's a bug due to the improper use of the `pygments` library.

For now, as a workaround, you can specify the syntax explicitly:

    ```bash
    #!/bin/bash
    echo "hello World"
    ```
